# Generated by Django 5.1.6 on 2025-03-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TryoutList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tryoutName', models.CharField(max_length=100)),
                ('tryoutDescp', models.CharField(max_length=100)),
                ('tryoutNums', models.IntegerField(max_length=100)),
            ],
        ),
    ]
