# Generated by Django 5.1.6 on 2025-03-04 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TryoutList',
            new_name='Tryout',
        ),
    ]
