# Generated by Django 5.1.6 on 2025-03-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_tryoutdescp_tryout_tryoutdesc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryout',
            name='category',
            field=models.CharField(default='Quiz', max_length=100),
        ),
        migrations.AddField(
            model_name='tryout',
            name='creationDate',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='tryout',
            name='workedOn',
            field=models.BooleanField(default=False),
        ),
    ]
