# Generated by Django 5.1.6 on 2025-03-04 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_tryout_category_tryout_creationdate_tryout_workedon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tryout',
            old_name='category',
            new_name='tryoutCategory',
        ),
    ]
