# Generated by Django 5.1.6 on 2025-03-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_tryout_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tryout',
            name='tryoutCategory',
            field=models.CharField(choices=[('Math and Natural Science', 'Math and Natural Science'), ('Social Science', 'Social Science'), ('Random', 'Random')], max_length=100),
        ),
    ]
