# Generated by Django 5.1.6 on 2025-03-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_tryout_tryoutcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tryout',
            name='tryoutCategory',
            field=models.CharField(max_length=100),
        ),
    ]
