# Generated by Django 5.1.6 on 2025-03-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_question_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionNum',
            field=models.IntegerField(default=1),
        ),
    ]
