# Generated by Django 5.1.6 on 2025-03-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_question_questionnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tryout',
            name='creationDate',
            field=models.DateField(editable=False, max_length=100),
        ),
    ]
