# Generated by Django 5.1.6 on 2025-03-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_tryout_tryoutnums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tryout',
            name='creationDate',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
