# Generated by Django 5.1.6 on 2025-03-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_tryout_creationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryout',
            name='bestResult',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tryout',
            name='latestResult',
            field=models.IntegerField(default=0),
        ),
    ]
