# Generated by Django 5.1.6 on 2025-03-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_tryout_bestresult_tryout_latestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choiceTxt_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='choiceTxt_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='choiceTxt_3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='choiceTxt_4',
            field=models.CharField(default='', max_length=100),
        ),
    ]
