# Generated by Django 5.1.6 on 2025-03-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_question_choicetxt_1_question_choicetxt_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='choiceTxt_1',
            new_name='choice1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choiceTxt_2',
            new_name='choice2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choiceTxt_3',
            new_name='choice3',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choiceTxt_4',
            new_name='choice4',
        ),
    ]
