# Generated by Django 5.1.6 on 2025-03-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_choicetxt_1_question_choice1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionType',
            field=models.CharField(default='TF', max_length=100),
        ),
    ]
