# Generated by Django 5.1.6 on 2025-03-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_question_questiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tryout',
            name='tryoutcreator',
            field=models.CharField(default='', max_length=100),
        ),
    ]
