# Generated by Django 5.1.6 on 2025-03-10 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_account_loggedinas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='loggedInAs',
        ),
    ]
