# Generated by Django 5.1.6 on 2025-03-10 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_account_loggedinas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tryout',
            old_name='tryoutcreator',
            new_name='tryoutCreator',
        ),
    ]
