# Generated by Django 5.1.6 on 2025-03-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_rename_tryoutcreator_tryout_tryoutcreator'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLoggedIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
