# Generated by Django 5.1.6 on 2025-03-10 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_accountloggedin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='AccountLoggedIn',
        ),
        migrations.RemoveField(
            model_name='tryout',
            name='tryoutCreator',
        ),
    ]
